### ISSUE TITLE
Android studio trigger check

### ISSUE THREAD

**Issue by jinfanzon** [johnthagen/clion-cppcheck#11]
### Environment

* Operating System Ubuntu 14.04 x64:
* IDE Version: Android studio
* Cppcheck executable version (`cppcheck --version`): 
* Cppcheck plugin version: Cppcheck 1.80
* Exact strings used in cppcheck plugin options:
  * **cppcheck path**: /usr/bin/cppcheck
  * **cppcheck options**: --enable=all,performance,portability,style,--language=c++

I've added your plugin to my IDE, but I was wondering how to trigger the check of the whole project

**Comment by johnthagen** [comment]
Did you follow the usage here? https://plugins.jetbrains.com/plugin/8143-cppcheck

Also, please fill in all of the environment details in the issue template.

**Comment by johnthagen** [comment]
Also, the plugin isn't designed to check the entire project, it checks files on demand as they are opened.

**Comment by johnthagen** [comment]
Actually, it looks like you can do this by running Code | Inspect Code...

**Comment by jinfanzon** [comment]
@johnthagen I've updated the environment details. I'll try the Inspect Code. but while I was testing the plugin I wrote:

int y[1];
y[2] = 1;

and no error was triggered on the fly

**Comment by johnthagen** [comment]
> Cppcheck plugin version: Cppcheck 1.80

That looks like the actually Cppcheck version, not the plugin version. Could you check the plugin version that is installed and then also verify the Cppcheck version itself?

Also if you could put the full version of Android Studio you are running.

**Comment by johnthagen** [comment]
@jinfanzon Did you resolve the issue? If so, I'll close the issue.
