### ISSUE TITLE
cppcheck warnings are always "Weak Warning" in highlighting

### ISSUE THREAD

**Issue by firewave** [johnthagen/clion-cppcheck#19]
### Environment

* Operating System (e.g. Ubuntu 16.04 x64): Windows 10
* IDE Version (e.g. CLion 2016.3.2): CLion 2018.2 EAP
* Cppcheck executable version (`cppcheck --version`): 1.84
* Cppcheck plugin version: 1.20
* Exact strings used in cppcheck plugin options:
  * **cppcheck path**: C:\Apps\cppcheck\cppcheck.exe
  * **cppcheck options**: --enable=warning,performance,portability --language=c++

### Expected behavior

The configured warning level should be used in the editor highlighting

### Actual behavior

The level is always "Weak Warning"

### Steps to reproduce the behavior

```
#include <string>

void func(const std::string s) {
    (void)s;
}

int main() {
    func("");
    return 0;
}
```

![cppcheck](https://user-images.githubusercontent.com/242857/42025774-ae7105f6-7ac5-11e8-989c-ae3a0d2072f1.jpg)

**Comment by johnthagen** [comment]
@firewave The warning level is based on the Cppcheck severity level: https://github.com/johnthagen/clion-cppcheck/blob/master/src/com/github/johnthagen/cppcheck/CppcheckInspection.java#L215

This way, the severity automatically changes based on the severity of the problem Cppcheck finds, and matches more closely to the types of things highlighted at those levels from other CLion inspections.

**Comment by johnthagen** [comment]
You can see the screenshot on the plugin page that shows the plugin outputting the Error severity level: https://plugins.jetbrains.com/plugin/8143-cppcheck

**Comment by johnthagen** [comment]
Going to close this as works as designed.
