### ISSUE TITLE
Problem: no error messages shown in Clion 2016.1

### ISSUE THREAD

**Issue by mbertini** [johnthagen/clion-cppcheck#2]
I've installed the plugin and I'm using cppcheck 1.73

If I try to check a simple:

#include <iostream>

using namespace std;

int main() {
    cout << "Hello, World!" << endl;
    int *p = new int;
    return 0;
}

In Clion I don't see any warning from cppcheck. If I run it manually I get a 

[temp3.cpp:8]: (error) Memory leak: p

Isn't it necessary to take away the leading ^ from the regex expression of the cppcheck message parser?

**Comment by johnthagen** [comment]
@mbertini What version of CLion are you running and on what OS?

Did you configure the paths for `cppcheck` according to the plugin page?

**Comment by mbertini** [comment]
I'm using 2016.1.1 and cppcheck 1.73 on OS X.
The path to the executable is OK: the only message I get from the plugin is, indeed, the error message if I do not use the correct path:

Error
IOException: Cannot run program "cppcheck": error=2, No such file or directory

**Comment by johnthagen** [comment]
@mbertini Unfortunately I don't have access to an OSX machine to test/debug.  Feels like a pathing issue.

I did verify the plugin works in CLion 2016.1.1 on Ubuntu 15.10 (about the closest I can get to OSX).

You could try putting the `cppcheck` directory in your global `$PATH` and then in the plugin putting just `cppcheck` for the cppcheck path configuration.

**Comment by johnthagen** [comment]
@mbertini Was able to test this on a Mac and confirmed that the plugin does work.  Please follow these steps:
- `brew install cppcheck`
- Set cppcheck path to `/usr/local/bin/cppcheck`
