### ISSUE TITLE
Doesn't work with the cppcheck(version 1.89)

### ISSUE THREAD

**Issue by haosu-c** [johnthagen/clion-cppcheck#24]
### Environment

* Operating System (macOS Mojave 10.14.5):
* IDE Version (CLion 2019.2.5):
* Cppcheck executable version (1.89): 
* Cppcheck plugin version:1.2.0
* Exact strings used in cppcheck plugin options:
  * **cppcheck path**:/usr/local/bin/cppcheck
  * **cppcheck options**: --enable=warning,performance,portability,style --language=c++

### Expected behaviour
work

### Actual behaviour
doesn't work

### Steps to reproduce the behaviour
1. Download and install cppcheck plugin from clion marketplace
2. restart clion
3. There is no effect when coding

The problem should be caused by a change in the output format.Because I downgrate cppcheck to 1.87, it works.

**Comment by johnthagen** [comment]
@haosu-c Sorry to hear this doesn't work. Unfortunately I haven't used `clion-cppcheck` personally in a long time (as is clear from the lack of maintenance). I would be happy to accept PR's to fix this though.

I suspect #9 would be more robust. When this plugin was originally created, simple command line output was parsed to finish it quickly, but it is clearly not robust.

**Comment by SJ-Innovation** [comment]
#25 I have created a candidate PR for a quick fix. I would also be interested in implementing #9 as it is a lot more of a robust solution.

**Comment by johnthagen** [comment]
Closed in #25

**Comment by johnthagen** [comment]
@haosu-c @SJ-Innovation plugin version 1.3.0 has been uploaded. It should be available in ~2 days after moderation.
