### ISSUE TITLE
Add MISRA Support

### ISSUE THREAD

**Issue by SJ-Innovation** [johnthagen/clion-cppcheck#26]
Add support in the configuration page, and when invoking cppcheck, of running MISRA checks. 

Unable to distribute MISRA rules texts, under the license which MISRA is distributed, this has to be obtained from them directly and parsed into a cppcheck readable format. This is left as an exercise to the user though.

**Comment by johnthagen** [comment]
Cppcheck plugin version 1.4.0 has been submitted for moderation. Thank you for your contribution.
