### ISSUE TITLE
Cppcheck could not run on the fly

### ISSUE THREAD

**Issue by YYurtcan** [johnthagen/clion-cppcheck#3]
Hi,
I am using clion for my project. I need static analyzer tool so I found cppcheck. I have downloaded it and integrated to clion. Integrated means;
1. File-->Settings-->Plugins after that import .jar file for cppcheck.
2. Settings->cppcheck configuration I gave absolute path 
After that I wrote some code, but static analyzer did not show anything.
What would be the reason?
Here is related informations;
- Operating System = Ubuntu 16.04
- CppCheck Version = 1.0.6
- CLion Version = 2016.2.2
- Exact string passed in the cppcheck options
         **cppcheck path** = Desktop/clion-2016.2.2/plugins/cppcheck/lib/cppcheck.jar
          **cppcheck options** = --enable=all --language = c++
Best regards.

**Comment by johnthagen** [comment]
@YYurtcan Thanks for the interest in the plugin.

1.  If you're Ubuntu machine is connected to the internet, it is much simpler to install the plugin through CLion itself (you don't need to manually download the .jar file). See https://www.jetbrains.com/help/idea/2016.3/installing-updating-and-uninstalling-repository-plugins.html.

2. The *cppcheck* path is the path to the [`cppcheck` executable](https://linux.die.net/man/1/cppcheck) (not the plugin). This plugin only integrates `cppcheck` into CLion, it does not bundle it. You probably want to install the Ubuntu package for cppcheck that already exists and it should place the executable into something like `/usr/local/bin/cppcheck`. I think the command you want is `apt-get install cppcheck`.

3. When you get cppcheck (the analyzer, not the plugin as described in step 2) installed, run `cppcheck --version`

Let me know if this solves your problem.

**Comment by YYurtcan** [comment]
It works.
Thank you,
