### ISSUE TITLE
"Show Clang Tidy Info" content being analyzed

### ISSUE THREAD

**Issue by firewave** [johnthagen/clion-cppcheck#38]
### Environment

* Operating System (e.g. Ubuntu 16.04 x64): Windows 10 Version 2004
* IDE Version (e.g. CLion 2016.3.2): CLion 2020.2 EAP (#CL-202.5103.16)
* Cppcheck executable version (`cppcheck --version`): 2.0
* Cppcheck plugin version: 1.4.2

### Expected behaviour

No analysis is performed.

### Actual behaviour

The analysis is performed and causes an error since the file is just a temporary one and no longer available for analysis.

### Steps to reproduce the behaviour

- open a file
- open the action dialog via `CTRL+SHIFT+A` and search for `Show Clang Tidy Info`
- the clan-tidy info will be shown and the error popup from the plugin appears

The issues is possibly caused by the title of the file tab ending with the file name i.e. the `.cpp` extension causing it to be passed to the analysis. There's probably a different mechanism to figure out the file type within the plugins.

**Comment by johnthagen** [comment]
For background, this plugin is using the file extension to determine if Cppcheck should be run against it:

https://github.com/johnthagen/clion-cppcheck/blob/ca1eab8ef83ece978185ee4d4ce9f33724f795e0/src/com/github/johnthagen/cppcheck/CppcheckInspection.java#L236-L260

**Comment by firewave** [comment]
I figured. I wonder if this is a limit of the `check()` function and fixed by the newer visitor implementation. Since the documentation of the SDK is lacking it's hard to tell. I already contacted JetBrains about this a while ago and I got a contact about CLion-specific SDK question. I didn't have the time to follow up on this but I still plan to.

**Comment by firewave** [comment]
I have a fix for this.
