### ISSUE TITLE
not working on osx 10.12.3 ?

### ISSUE THREAD

**Issue by wenxingxing** [johnthagen/clion-cppcheck#5]
### Environment

* Operating System: osx 10.12.3
* IDE Version : 2016.3.2
* Cppcheck executable version (`cppcheck --version`): 1.77
* Cppcheck plugin version: 1.07
* Exact strings used in cppcheck plugin options:
  * **cppcheck path**: /usr/local/bin/cppcheck
  * **cppcheck options**: --enable=warning,performance,portability,style, --language=c++

### Expected behaviour
report an error for this
```c++
int main() {
  int x[1];
  x[2] = 1;
}
```

### Actual behaviour
didn't get any error msg

**Comment by johnthagen** [comment]
Just tested on OSX 10.11.6 and CLion 2016.3.3 and it worked as expected.

I installed Cppcheck with [Homebrew](https://brew.sh/).

```bash
$ brew update
$ brew install cppcheck
```

Installed the Cppcheck CLion plugin and configured the path for cppcheck in Settings > Other Settings > cppcheck configuration.

Did you configure the plugin after installing it?

**Comment by wenxingxing** [comment]
Yes, i did. Here is my configuration.

![img](http://snappyimages.nextwavesrl.netdna-cdn.com/img/b4dd80f05cc73943202749e33bd7a694.png)

![img](http://snappyimages.nextwavesrl.netdna-cdn.com/img/5e4fbdc04cbc57dc04c31c1ad0fd6a42.png)

![img](http://snappyimages.nextwavesrl.netdna-cdn.com/img/78bed273334ec4315c4b8a3936de3141.png)

![img](http://snappyimages.nextwavesrl.netdna-cdn.com/img/5621b0d416bb86cdd792a8b844617e8a.png)

And the result.

![img](http://snappyimages.nextwavesrl.netdna-cdn.com/img/1de0159abbbe1ba04bc666842c577ea4.png)

**Comment by wenxingxing** [comment]
Oh, i know what's wrong. I got an extra comma in the options. 

with `--enable=warning,performance,portability,style --language=c++`, it works fine. 

Thanks, amazing plugin!

**Comment by johnthagen** [comment]
Great, glad it's working out for you.
