### ISSUE TITLE
Ensure plugin works with CLion 2020.3

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/clion-cppcheck#64]
See: https://plugins.jetbrains.com/plugin/8143-cppcheck/reviews

> Please check if the plugin works with latest CLion (>=2020.3). For me it says "No suspicious code found". Though for some earlier version it was working. Tested with both 1.5.1 and 1.6.0 (master)

@firewave If you happen to have any cycles, wanted to bring this to your attention.

**Comment by firewave** [comment]
I am using 2020.3 on a daily basis (cannot move to 2021.1 yet due to a bug) and it worked fine with Cppcheck 2.3 and 2.4 releases on Windows 10.

**Comment by johnthagen** [comment]
Okay. I will go ahead and close this issue until we actually can reproduce any issue (if one even exists). Thanks for the quick response.
