### ISSUE TITLE
Unable to build 1.6.0 on Windows

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/clion-cppcheck#66]
@firewave I am unable to build the current `master` branch on Windows with IntelliJ 2021.3. The compile errors I get:

```
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:14:32
java: package org.apache.commons.lang3 does not exist
```

```
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:57:48
java: cannot find symbol
  symbol:   variable RandomStringUtils
  location: class com.github.johnthagen.cppcheck.CppcheckInspection
```

Do you build  from Linux where this is an implicitly installed? I think we either need to properly reference this in the build so it's pulled down on any system when we build, or remove this reference (perhaps replacing with a simple implementation of this function ourselves).

After this is resolved, I'll release 1.6.0 (or 1.6.1).

Also, I did a little research and `RandomStringUtils` also appears to be deprecated: https://stackoverflow.com/a/20536590

**Comment by johnthagen** [comment]
This change was made in #56

**Comment by firewave** [comment]
I think they dropped that package from the SDK a while back. I faintly remember seeing such an error the last time I opened it in the IDE (which was quite a while ago).

I will try to take a look in the next few days.

**Comment by firewave** [comment]
> Also, I did a little research and `RandomStringUtils` also appears to be deprecated: https://stackoverflow.com/a/20536590

It's not - https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html

```
RandomStringUtils is intended for simple use cases. For more advanced use cases consider using Apache Commons Text's RandomStringGenerator instead.
```

I assume to get that dependency we need to package it ourselves and add it to the repo for now. But it's been so long since I added a dependency to a Java project I need to figure out how to do it again. :D

The proper way would probably using a gradle file which just pulls the dependency in - see https://github.com/conan-io/conan-clion-plugin/blob/dev/build.gradle

**Comment by johnthagen** [comment]
@firewave I tried to build the project after #67 was merged, but I still get a build error on the latest `master`.

```
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:14:32
java: package org.apache.commons.lang3 does not exist
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:57:48
java: cannot find symbol
  symbol:   variable RandomStringUtils
  location: class com.github.johnthagen.cppcheck.CppcheckInspection
```

- IntelliJ IDEA 2021.3.1 (Community Edition)
- Windows 10

I also see problems in IntelliJ window:

<img width="518" alt="Screenshot 2022-01-10 190354" src="https://user-images.githubusercontent.com/10340167/148858383-4d698ef7-2e10-42a6-8544-13d9edd90e1a.png">

<img width="767" alt="Screenshot 2022-01-10 190528" src="https://user-images.githubusercontent.com/10340167/148858509-a88515fa-b7ff-417f-9700-46eb484b9f4a.png">

I still think the easiest solution could be to remove the dependency and use some kind of built in random number generator to make a random file name.

**Comment by firewave** [comment]
I forgot to add the library file.
