### ISSUE TITLE
Cppcheck execution failed

### ISSUE THREAD

**Issue by DADi590** [johnthagen/clion-cppcheck#73]
### Environment

* Operating System (e.g. Ubuntu 16.04 x64): Windows 10 Build 1809 x64
* IDE Version (e.g. CLion 2016.3.2): CLion 2021.3.2
* Cppcheck executable version (`cppcheck --version`): 2.6
* Cppcheck plugin version: 1.6.2
* Exact strings used in cppcheck plugin options:
  * **cppcheck path**: C:\Program Files\Cppcheck\cppcheck.exe
  * **cppcheck options**: --enable=style,performance,portability,information,missingInclude --language=c --inconclusive --inline-suppr --report-progress --std=c89 --verbose --version

### Expected behaviour
That it would analyze the code normally, which I'm not sure if it does.

### Actual behaviour
I'm not sure if it analyzes the code (I don't see any Cppcheck warnings - so not sure it's the code that it's good or the plugin that it's not working), but it throws an error every time it attempts to analyze the code:
```
Cppcheck execution failed: [project path here, probably - I can't see it all, it's cut after a big and there's no expanding option]
SAXParseException: Premature end of file.
```
Normally this error happens twice in a row, if that helps (a second between each of them).

### Steps to reproduce the behaviour
No idea, it happens with any project I open, so I think it's not normal this would happen. Every time I change some line and save, the 2 errors appear again.

**Comment by firewave** [comment]
The `--version` in the command-line causes Cppcheck to do nothing and just return its version instead. Hence the error parsing the XML output.

**Comment by DADi590** [comment]
Wow. I'm dumb, never mind. Sorry to bother you. Thanks though, and thank you for the plugin!

**Comment by firewave** [comment]
> Wow. I'm dumb, never mind. Sorry to bother you. Thanks though, and thank you for the plugin!

No problem. This just highlights that the configuration is *awkward* and needs to be improved at some point.
