### ISSUE TITLE
Add the ability to configure the plugin for only one project

### ISSUE THREAD

**Issue by tocic** [johnthagen/clion-cppcheck#89]
I keep getting an internal error from `cppcheck` for my project. Can I disable the plugin or suppress files only for that project? In some other plugins, you have the option to configure on a per-project basis. I'd like to have it here too.

**Comment by firewave** [comment]
This is essentially a duplicate of #52.

Also could you provide some information on the "internal error"? Is it an error from the Cppcheck analysis or from the plugin?

**Comment by tocic** [comment]
From the Cppcheck analysis. OK, closing then.

**Comment by firewave** [comment]
Care to share the internal error? That issue is not related to the plugin but it also needs to be resolved.

**Comment by tocic** [comment]
I've already reported it to the cppcheck team. It's not easy to reproduce it now: more than 2 months have passed + I don't use CLion currently.

**Comment by firewave** [comment]
Good to know. Could you point me to the report?

The only `internalError` I am aware of is https://trac.cppcheck.net/ticket/11708 and that is fixed with 2.11. That should not have been visible with 2.10 though.

**Comment by tocic** [comment]
> Could you point me to the report?

No, sorry.
