### ISSUE TITLE
Compatibility verification issue with 2019.2 and 2019.3

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/clion-cppcheck#94]
Version 1.6.3 upload was delayed and JetBrains asked us to look into the following compatibility issue.

My recommendation would be to simply increase the minimum supported IntelliJ version to 2020.1.

Then we could bump to 1.6.4, rebuild, and resubmit.

### IntelliJ IDEA Ultimate 2019.3.5 compatibility problem

1 compatibility problem

cppcheck 1.6.3 is binary incompatible with IntelliJ IDEA Ultimate IU-193.7288.26 due to the following problem

Dependency on Java plugin is not specified (1 problem)

Plugin uses classes of Java plugin, for example
`RandomStringUtils` is used at `CppcheckInspection.checkFile(...)`
but the plugin does not declare explicit dependency on the Java plugin, via <depends>com.intellij.modules.java</depends>.
Java functionality was extracted from the IntelliJ Platform to a separate plugin in IDEA 2019.2.
For more info refer to https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin

**Comment by firewave** [comment]
This is a duplicate of #70.

**Comment by johnthagen** [comment]
Closing as duplicate of

- #70
